const DEITIES = [
  {
    id: 'shiva',
    name: 'शिव',
    english: 'Shiva',
    icon: 'moon',
    color: '#6366F1',
    mantra: 'Om Namah Shivaya',
    description: 'The destroyer and transformer. Lord of meditation, yoga, and arts. The supreme being who creates, protects and transforms the universe.',
    aarti: 'Jai Shiv Omkara, Jai Shiv Omkara. Brahma Vishnu Sadashiv, Ardhangi Dhara.',
  },
  {
    id: 'vishnu',
    name: 'विष्णु',
    english: 'Vishnu',
    icon: 'flower',
    color: '#0EA5E9',
    mantra: 'Om Namo Bhagavate Vasudevaya',
    description: 'The preserver and protector of the universe. He descends to earth in various avatars to restore cosmic order.',
    aarti: 'Jai Jagdish Hare, Swami Jai Jagdish Hare. Bhakt jano ke sankat, daas jano ke sankat, kshan mein door kare.',
  },
  {
    id: 'durga',
    name: 'दुर्गा',
    english: 'Durga',
    icon: 'shield',
    color: '#F97316',
    mantra: 'Om Dum Durgayei Namaha',
    description: 'The divine mother and warrior goddess. She embodies feminine power and protects her devotees from all evil.',
    aarti: 'Jai Ambe Gauri, Maiya Jai Shyama Gauri. Tumko nishdin dhyavat, Hari Brahma Shivari.',
  },
  {
    id: 'ganesh',
    name: 'गणेश',
    english: 'Ganesh',
    icon: 'star',
    color: '#F59E0B',
    mantra: 'Om Gam Ganapataye Namaha',
    description: 'The remover of obstacles and god of beginnings. He is worshipped before any important endeavor.',
    aarti: 'Jai Ganesh Jai Ganesh, Jai Ganesh Deva. Mata Jaki Parvati, Pita Mahadeva.',
  },
  {
    id: 'krishna',
    name: 'कृष्ण',
    english: 'Krishna',
    icon: 'musical-note',
    color: '#8B5CF6',
    mantra: 'Hare Krishna Hare Krishna, Krishna Krishna Hare Hare',
    description: 'The divine lover, friend, and guide. The eighth avatar of Vishnu, who revealed the Bhagavad Gita to Arjuna.',
    aarti: 'Aarti Kunj Bihari Ki, Shri Girdhar Krishna Murari Ki.',
  },
  {
    id: 'hanuman',
    name: 'हनुमान',
    english: 'Hanuman',
    icon: 'flame',
    color: '#EF4444',
    mantra: 'Om Hanumate Namah',
    description: 'The devoted disciple of Lord Rama. Symbol of strength, devotion, and selfless service.',
    aarti: 'Aarti Kije Hanuman Lala Ki, Dushta Dalan Raghunath Kala Ki.',
  },
];

export default DEITIES;