export const GITA_CHAPTERS = [
  { id: 1, title: 'Arjuna Vishada Yoga', hindi: 'अर्जुन विषाद योग', verses: 47, summary: 'Arjuna sees his relatives on the opposing army side and is overcome with grief and confusion. He drops his bow and refuses to fight.' },
  { id: 2, title: 'Sankhya Yoga', hindi: 'सांख्य योग', verses: 72, summary: 'Krishna begins his teachings. He explains the immortality of the soul, the nature of duty, and introduces the concept of Karma Yoga.' },
  { id: 3, title: 'Karma Yoga', hindi: 'कर्म योग', verses: 43, summary: 'Krishna explains the path of selfless action. One must perform their duty without attachment to results.' },
  { id: 4, title: 'Jnana Karma Sanyasa Yoga', hindi: 'ज्ञान कर्म संन्यास योग', verses: 42, summary: 'Krishna reveals the divine nature of his births and deeds. He explains the importance of wisdom and sacrifice.' },
  { id: 5, title: 'Karma Sanyasa Yoga', hindi: 'कर्म संन्यास योग', verses: 29, summary: 'Krishna compares renunciation of action with the yoga of action and explains that both lead to liberation.' },
  { id: 6, title: 'Dhyana Yoga', hindi: 'ध्यान योग', verses: 47, summary: 'Krishna explains the practice of meditation and describes the characteristics of a true yogi.' },
  { id: 7, title: 'Jnana Vijnana Yoga', hindi: 'ज्ञान विज्ञान योग', verses: 30, summary: 'Krishna explains how He is the ultimate reality and how everything in existence is a manifestation of his divine energy.' },
  { id: 8, title: 'Aksara Brahma Yoga', hindi: 'अक्षर ब्रह्म योग', verses: 28, summary: 'Krishna explains the nature of Brahman, karma, and how to attain the supreme state at the time of death.' },
  { id: 9, title: 'Raja Vidya Yoga', hindi: 'राज विद्या योग', verses: 34, summary: 'Krishna reveals the most confidential knowledge — the path of devotion and how the universe is sustained by Him.' },
  { id: 10, title: 'Vibhuti Yoga', hindi: 'विभूति योग', verses: 42, summary: 'Krishna describes his divine manifestations and explains that all beautiful and glorious things are but a spark of his splendor.' },
  { id: 11, title: 'Vishvarupa Darsana Yoga', hindi: 'विश्वरूप दर्शन योग', verses: 55, summary: 'Krishna grants Arjuna divine vision and reveals his universal form — a spectacular and awe-inspiring cosmic vision.' },
  { id: 12, title: 'Bhakti Yoga', hindi: 'भक्ति योग', verses: 20, summary: 'Krishna glorifies the path of devotion and describes the qualities of his dear devotees.' },
  { id: 13, title: 'Kshetra Kshetrajna Vibhaga Yoga', hindi: 'क्षेत्र क्षेत्रज्ञ विभाग योग', verses: 35, summary: 'Krishna explains the distinction between the body and the soul, and the nature of the field and the knower of the field.' },
  { id: 14, title: 'Gunatraya Vibhaga Yoga', hindi: 'गुणत्रय विभाग योग', verses: 27, summary: 'Krishna explains the three modes of material nature — goodness, passion, and ignorance — and their effects on beings.' },
  { id: 15, title: 'Purushottama Yoga', hindi: 'पुरुषोत्तम योग', verses: 20, summary: 'Krishna describes the cosmic tree of existence and explains the nature of the supreme person beyond the perishable and imperishable.' },
  { id: 16, title: 'Daivasura Sampad Vibhaga Yoga', hindi: 'दैवासुर सम्पद् विभाग योग', verses: 24, summary: 'Krishna distinguishes between divine and demoniac qualities and urges Arjuna to follow the path of virtue.' },
  { id: 17, title: 'Shraddhatraya Vibhaga Yoga', hindi: 'श्रद्धात्रय विभाग योग', verses: 28, summary: 'Krishna explains the three types of faith corresponding to the three modes of nature.' },
  { id: 18, title: 'Moksha Sanyasa Yoga', hindi: 'मोक्ष संन्यास योग', verses: 78, summary: 'The concluding chapter. Krishna summarizes all his teachings and urges Arjuna to rise and fulfill his duty.' },
];