const WALLPAPERS = [
  {
    id: 'shiva_1',
    deity: 'Shiva',
    title: 'Mahadev',
    color: '#6366F1',
    gradient: ['#1e1b4b', '#4338ca'],
    icon: 'moon',
    category: 'wallpaper',
  },
  {
    id: 'shiva_2',
    deity: 'Shiva',
    title: 'Om Namah Shivaya',
    color: '#6366F1',
    gradient: ['#312e81', '#6366f1'],
    icon: 'moon',
    category: 'status',
  },
  {
    id: 'hanuman_1',
    deity: 'Hanuman',
    title: 'Jai Bajrangbali',
    color: '#EF4444',
    gradient: ['#7f1d1d', '#ef4444'],
    icon: 'flame',
    category: 'wallpaper',
  },
  {
    id: 'hanuman_2',
    deity: 'Hanuman',
    title: 'Sankat Mochan',
    color: '#EF4444',
    gradient: ['#991b1b', '#f87171'],
    icon: 'flame',
    category: 'status',
  },
  {
    id: 'krishna_1',
    deity: 'Krishna',
    title: 'Radhe Krishna',
    color: '#8B5CF6',
    gradient: ['#2e1065', '#7c3aed'],
    icon: 'musical-note',
    category: 'wallpaper',
  },
  {
    id: 'krishna_2',
    deity: 'Krishna',
    title: 'Hare Krishna',
    color: '#8B5CF6',
    gradient: ['#4c1d95', '#a78bfa'],
    icon: 'musical-note',
    category: 'status',
  },
  {
    id: 'durga_1',
    deity: 'Durga',
    title: 'Jai Mata Di',
    color: '#F97316',
    gradient: ['#7c2d12', '#ea580c'],
    icon: 'shield',
    category: 'wallpaper',
  },
  {
    id: 'durga_2',
    deity: 'Durga',
    title: 'Durga Maa',
    color: '#F97316',
    gradient: ['#9a3412', '#fb923c'],
    icon: 'shield',
    category: 'status',
  },
  {
    id: 'ganesh_1',
    deity: 'Ganesh',
    title: 'Ganpati Bappa',
    color: '#F59E0B',
    gradient: ['#78350f', '#d97706'],
    icon: 'star',
    category: 'wallpaper',
  },
  {
    id: 'ganesh_2',
    deity: 'Ganesh',
    title: 'Shubh Labh',
    color: '#F59E0B',
    gradient: ['#92400e', '#fbbf24'],
    icon: 'star',
    category: 'status',
  },
  {
    id: 'vishnu_1',
    deity: 'Vishnu',
    title: 'Narayan Narayan',
    color: '#0EA5E9',
    gradient: ['#0c4a6e', '#0284c7'],
    icon: 'flower',
    category: 'wallpaper',
  },
  {
    id: 'vishnu_2',
    deity: 'Vishnu',
    title: 'Om Namo Narayana',
    color: '#0EA5E9',
    gradient: ['#075985', '#38bdf8'],
    icon: 'flower',
    category: 'status',
  },
];

export const CATEGORIES = ['all', 'wallpaper', 'status'];
export const DEITIES_FILTER = ['all', 'Shiva', 'Hanuman', 'Krishna', 'Durga', 'Ganesh', 'Vishnu'];

export default WALLPAPERS;